### ISSUE TITLE
orphaning Debian package of harmony

### ISSUE THREAD

**Issue by pabs3** [taylordotfish/harmony#19]
I am soon going to be stopping using harmony.
So I will be orphaning the Debian package of it.
If anyone wants to adopt it, I can help you get started, sponsor it etc.
If no-one wants to adopt it, I wonder if I should remove it from Debian?

**Comment by taylordotfish** [comment]
I currently don't have the bandwidth to maintain the Debian package, but I'm also happy to let anyone who's interested do so. Otherwise, if there's no interest, I'm okay with removing it.

**Comment by JacobKfromIRC** [comment]
If you don't mind me asking, @pabs3 , did you switch to a different Discord program (which one?), or did you stop using Discord entirely? Ever since Discord switched to hCaptcha, I've occasionally tried looking for a different way to login with free software, but I didn't find anything. I tried to start developing a [Haketilo](https://haketilo.koszko.org/) package for hCaptcha, but [I didn't get very far](https://codeberg.org/JacobK/unfinished-site-fixes/src/branch/main/hCaptcha/hcaptcha-demo.js).

**Comment by pabs3** [comment]
I plan to stop using Discord entirely and delete my account soon.

My account is from before the use of hCaptcha so I haven't encountered
that issue yet. Harmony still works without a captcha here, hopefully
deletion will work without one too, from what I hear, it probably will.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by JacobKfromIRC** [comment]
Thank you,

I suppose I should clarify that I can still technically login, and I was even able to use Discord normally for months after the switch to hCaptcha, but I guess at some point Discord decided I was a bot, and now I can only read messages, not send messages, join/leave channels, or accept/deny friend requests.

**Comment by pabs3** [comment]
I read that situation requires you to login on the web, possibly enter
a non-VoIP real/mobile phone number, then you probably will get your
account working again. I've never had that myself though.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
I have now orphaned the Debian package of harmony:

https://bugs.debian.org/1032369

Please comment here or contact me for help taking it over.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
@Nardol since you recently adopted the Debian purple-discord package, perhaps you would like to adopt the Debian harmony package too?

**Comment by Nardol** [comment]
@pabs3 Yes, it is on my mind and I am working on it but I am facing #20 which makes me hesitating to make a Debian package for a tool I cannot successfully use myself.

@jeremyp3 as you tested and was able to log-in with the version actually available on Debian, so maybe I can build the package and send it to you to test?
Because it is a new version if I believe in the last tag.

@pabs3 what is your opinion on this process?
Looks strange to me but I am known to ask myself too much question :slightly_smiling_face:

**Comment by jeremyp3** [comment]
@Nardol don't worry about sending me the package, I'll test it.

**Comment by Nardol** [comment]
@jeremyp3 by sending a package I mind the one with the new version I would plan to send for Debian unstable when adopting the actually orphaned package.

**Comment by pabs3** [comment]
@Nardol yeah it makes sense to wait until harmony works for you before
adopting the Debian package.

**Comment by Nardol** [comment]
As @jeremyp3 confirmed me privately he tested my package successfully, I confirmed my intent to adopt Harmony Debian package.

**Comment by Nardol** [comment]
Harmony 0.7.2 has been accepted into Unstable: https://tracker.debian.org/news/1485354/accepted-harmony-072-1-source-into-unstable/

Maybe this issue can be closed?
Thanks @pabs3 for the help because I was really beginning in my knowledge in Debian packaging for official packages.

**Comment by pabs3** [comment]
@Nardol has adopted the Debian harmony package, I will be sponsoring uploads.
